### ISSUE TITLE
mptcpd 0.7 on linux kernel 5.10.0

### ISSUE THREAD

**Issue by VenkateswaranJ** [intel/mptcpd#128]
I have compiled mptcpd release 0.7 on ubuntu 20.04 (kernel - 5.10.0), but when I try to run it I'm getting below warning

```
ip@ip-VirtualBox:~/$ sudo src/mptcpd --debug
configuration.c:mptcpd_config_create() plugin directory: /usr/local/lib/mptcpd
configuration.c:mptcpd_config_create() default path manager plugin: addr_adv
path_manager.c:family_appeared() "mptcp_pm" generic netlink family appeared
**Unable to register handler for mptcp_pm_events multicast messages**        // warning line
MPTCP single-subflow-per-interface path manager initialized.
MPTCP address advertiser path manager initialized.
```
which means mptcpd can't listen to pm Netlink events from kernel space? As you can see, I'm running it as the **root user**. 
I have two interfaces on both client and server and only the first interface being used as Master subflow and I expect **sspi** path manager plugins will detect the second interface on both sides and create the second subflow between them but it's not happening.

Apologise for asking questions on the GitHub issue page but I couldn't find any other medium to get help on this repo.

**Comment by ossama-othman** [comment]
Hi,

> I have compiled mptcpd release 0.7 on ubuntu 20.04 (kernel - 5.10.0), but when I try to run it I'm getting below warning
> ```
> **Unable to register handler for mptcp_pm_events multicast messages**        // warning line
>```
> which means mptcpd can't listen to pm Netlink events from kernel space? As you can see, I'm running it as the **root user**.
> I have two interfaces on both client and server and only the first interface being used as Master subflow and I expect **sspi** path manager plugins will detect the second interface on both sides and create the second subflow between them but it's not happening.

The MPTCP generic netlink events weren't available in the Linux kernel until the v5.12 release, which is why mptcpd was unable to listen for MPTCP events in your v5.10 kernel.  I suppose the log message could be improved a bit.  :)

The corresponding diff of the `<linux/mptcp.h>` user API header showing the event related changes is available [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/include/uapi/linux/mptcp.h?id=v5.12&id2=v5.11).  

> Apologise for asking questions on the GitHub issue page but I couldn't find any other medium to get help on this repo.

No worries.  Submitting a GitHub issue for this sort of question about mptcpd is fine.  There is also the [mptcp mailing list](https://subspace.kernel.org/lists.linux.dev.html?highlight=mptcp) hosted on lists.linux.dev.  It is mostly used for MPTCP related kernel development discussions, but mptcpd related questions are also fine for that list as well.

**Comment by ossama-othman** [comment]
> I expect sspi path manager plugins will detect the second interface on both sides and create the second subflow between them but it's not happening.

I should also mention that there is currently an issue open regarding subflow creation in the "sspi" plugin.  See issue #123.

**Comment by VenkateswaranJ** [comment]
Thanks for your comments, I tried with 5.10.0 kernel and I can able to listen to Netlink events. Just one last question before closing this issue. 
Does MPTCP out-of-tree implementation has this similar kind of Netlink events or it's only available in upstream implementation?

**Comment by ossama-othman** [comment]
Yes, it does.  In fact, the upstream kernel's MPTCP path management generic netlink _event_ API is based on the out-of-tree multipath-tcp.org kernel's event API.  Other than multicast group names, there is no difference between the two event APIs.  However, the generic netlink command API does currently differ.  The upstream kernel's command API is server-oriented, where path management is performed within the kernel at a global level.  The multipath-tcp.org kernel's command API is more client-oriented, and allows per-connection path management to be performed in the user space.  Work in mptcpd is currently under way to make the command differences more explicit.  In particular, the `ADD_ADDR` and `REMOVE_ADDR` related mptcpd library functions will be split into client- and server-oriented ones, removing the overlap.

**Comment by VenkateswaranJ** [comment]
Thanks, Ossama for the detailed comment.
