### ISSUE TITLE
Ignore virtual interfaces

### ISSUE THREAD

**Issue by dulive** [intel/mptcpd#175]
Currently, `mptcpd` does not ignore virtual interfaces, which leads to `mptcpd` announcing events related to them to the plugins (as for example address). This is somewhat annoying when using `mptcpd` and a network emulator that creates a bunch of virtual interfaces at the same time.

For example, with the `addr_adv` path manager, endpoints are configured for these interfaces.
Ex:
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
    link/ether 88:d7:f6:1b:2d:80 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether 3c:95:09:20:7d:5c brd ff:ff:ff:ff:ff:ff
14: b.6.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 22:3b:0a:dc:2b:0d brd ff:ff:ff:ff:ff:ff
16: veth1.0.1@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.6.1 state UP mode DEFAULT group default qlen 1000
    link/ether 22:3b:0a:dc:2b:0d brd ff:ff:ff:ff:ff:ff link-netnsid 0
18: veth2.0.1@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.6.1 state UP mode DEFAULT group default qlen 1000
    link/ether ee:db:d1:cb:5a:ac brd ff:ff:ff:ff:ff:ff link-netnsid 1
19: b.7.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 7a:54:1d:09:70:3c brd ff:ff:ff:ff:ff:ff
21: veth2.1.1@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.7.1 state UP mode DEFAULT group default qlen 1000
    link/ether b2:b3:66:c0:01:55 brd ff:ff:ff:ff:ff:ff link-netnsid 1
23: veth3.0.1@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.7.1 state UP mode DEFAULT group default qlen 1000
    link/ether 7a:54:1d:09:70:3c brd ff:ff:ff:ff:ff:ff link-netnsid 2
24: b.8.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 4a:56:09:53:8c:bb brd ff:ff:ff:ff:ff:ff
26: veth2.2.1@if25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.8.1 state UP mode DEFAULT group default qlen 1000
    link/ether aa:58:86:d8:ff:1e brd ff:ff:ff:ff:ff:ff link-netnsid 1
28: veth4.0.1@if27: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.8.1 state UP mode DEFAULT group default qlen 1000
    link/ether 4a:56:09:53:8c:bb brd ff:ff:ff:ff:ff:ff link-netnsid 3
29: b.9.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 96:ad:82:3a:f8:50 brd ff:ff:ff:ff:ff:ff
31: veth3.1.1@if30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.9.1 state UP mode DEFAULT group default qlen 1000
    link/ether 96:ad:82:3a:f8:50 brd ff:ff:ff:ff:ff:ff link-netnsid 2
33: veth5.0.1@if32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.9.1 state UP mode DEFAULT group default qlen 1000
    link/ether aa:fc:38:22:60:ce brd ff:ff:ff:ff:ff:ff link-netnsid 4
34: b.10.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2a:ab:75:b7:f1:c5 brd ff:ff:ff:ff:ff:ff
36: veth4.1.1@if35: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.10.1 state UP mode DEFAULT group default qlen 1000
    link/ether 2a:ab:75:b7:f1:c5 brd ff:ff:ff:ff:ff:ff link-netnsid 3
38: veth5.1.1@if37: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master b.10.1 state UP mode DEFAULT group default qlen 1000
    link/ether 82:00:3a:f4:59:06 brd ff:ff:ff:ff:ff:ff link-netnsid 4
```
before running `mptcpd`
```
$ ip mptcp endpoint show
```
after running `mptcpd --path-manager=addr_adv --notify-flags=existing`
```
$ ip mptcp endpoint show
172.26.101.243 id 1 dev wlan0
fe80::b5cb:f483:435c:d5f1 id 2 dev wlan0
fe80::a8a0:47ff:fed3:7a23 id 3 dev b.6.1
fe80::fb21:6a39:8027:a4a1 id 4 dev veth1.0.1
fe80::5e95:c1f0:c6d6:207d id 5 dev veth2.0.1
fe80::d467:d7ff:fecb:52c5 id 6 dev b.7.1
fe80::5b31:1b9c:8951:f181 id 7 dev veth2.1.1
fe80::b168:4b04:34ad:d4b2 id 8 dev veth3.0.1
```

In this example using the `notify-flag` `skip_link_local` would fix the problem, but if someone doesn't want to use the flag the problem persist.

If this behavior is expected, it maybe should be optional.

**Comment by ossama-othman** [comment]
From a brief discussion on the `#mptcp` IRC channel on Libera.Chat:

@pabeni said:
> I *think* that the answer is "it depends" as usual :), e.g. mptcpd could potentially run in netns with network connectivity only via veth[s] (well that is tricky...).  Even VLANs are virtual devices, and we likely want mptcpd to use IP addresses present there, if any.  I *think* that we could handle the above with ACLs on the monitored devices list, e.g. a list of network devices name to be ignored, or a list of nics to be managed.

@matttbe said:
> I agree with @pabeni. Probably easier with a list given in the configuration. By default, all interfaces would be used.

**Comment by dulive** [comment]
Running mptcp in a netns would make it need to use the virtual devices (as for example running mptcpd inside of an emulation environment), but isn't a list of network devices to be ignored too much? This because I can't think of a situation where someone would like that both physical and virtual devices would be used. In a netns there would be only virtual devices (if I'm not wrong), so it could probably just be an option to ignore or to use virtual devices.

**Comment by matttbe** [comment]
It might be enough for the moment but I don't see why you could not have a mix:
- in a netns, you can add a physical device in
- you can have interfaces with a vlan and some without
- you can even set a "public" IP on a loopback interface if the host is behind a NAT or similar.
- etc.

**Comment by dulive** [comment]
I probably was not clear in that statement. I was referring to `mptcpd`, that I couldn't think of a situation where the use of both physical devices and virtual devices by the `mptcpd` would be desired. I was not referring outside, in the example I have on my first comment I have a mix of both type of devices.

> in a netns, you can add a physical device in
That's interesting, I didn't know that.
But now that you referred it, if it is possible then someone could want to ignore physical devices inside of a netns. In that case a list would be better indeed.

**Comment by dulive** [comment]
I've been thinking, wouldn't a list of network devices to ignore in the configuration be useless with the case of my first comment, where virtual devices where created by using a network emulator?
When virtual devices are dynamically created or simply created after the execution of `mptcpd`, one can't guess what will be the name of the virtual devices to ignore.

**Comment by pabeni** [comment]
> I've been thinking, wouldn't a list of network devices to ignore in the configuration be useless with the case of my first comment, where virtual devices where created by using a network emulator? When virtual devices are dynamically created or simply created after the execution of `mptcpd`, one can't guess what will be the name of the virtual devices to ignore.

wildcards for interface name could be supported easily, e.g. "veth*"

Anyway I now think there is better solution for this, which is implementing #170. Interface/address without associated default route will be automatically ignored. With common/simple setup ("main" IPs acquired via dhcp) that should just work.

**Comment by dulive** [comment]
That works.

Thank you.
