### ISSUE TITLE
packaging for nixos

### ISSUE THREAD

**Issue by teto** [intel/mptcpd#188]
**Describe the bug**
Hi, I am trying to package this for nixos but I dont know about autoconf and I have some issues. Package defined in https://github.com/teto/mptcp-flake/pull/1/files#diff-443bc1da948f07bd678690aa687faa54f54cdd113290f65548842c0017049720

**To Reproduce**
with gcc as compiler, I get the error
```
autoreconf --install --symlink --force -v
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --force
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
autoreconf: running: /nix/store/x5q70zjlassqa65m616cqdra18yvxl9z-autoconf-2.71/bin/autoconf --force
configure.ac:102: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /nix/store/x5q70zjlassqa65m616cqdra18yvxl9z-autoconf-2.71/bin/autoconf failed with exit status: 1
```
If I comment out these lines
```
# Enable address sanitizer support.
MPTCPD_ADD_ASAN_SUPPORT

# Enable leak sanitizer support.
MPTCPD_ADD_LSAN_SUPPORT

# Enable undefined behavior sanitizer support.
MPTCPD_ADD_UBSAN_SUPPORT

```

I can go further but I still get:
```
(ins)➜ autoreconf --install --symlink --force -v
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --force
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
autoreconf: running: /nix/store/x5q70zjlassqa65m616cqdra18yvxl9z-autoconf-2.71/bin/autoconf --force
autoreconf: running: /nix/store/x5q70zjlassqa65m616cqdra18yvxl9z-autoconf-2.71/bin/autoheader --force
autoreconf: running: automake --add-missing --force-missing
configure.ac:32: installing './compile'
configure.ac:30: installing './missing'
automake: error: cannot open < aminclude_static.am: No such file or directory
autoreconf: error: automake failed with exit status: 1
```

nixos is a very special distribution (yet one with the most available and fresh packages) so I must call autoconf to regenerate the configure. I am using the current master 2097bd2b00e240ee1126fa69ce525c18c95a2ec4.

**Comment by ossama-othman** [comment]
I'm guessing that you're running into backward compatibility breaks introduced in [Autoconf 2.70+](https://lists.gnu.org/archive/html/autotools-announce/2020-12/msg00001.html) since the mptcpd `configure` script was developed against Autoconf 2.69.  I'll try to reproduce the problem on my end.

**Comment by teto** [comment]
i can confirm it runs `autoreconf (GNU Autoconf) 2.71`. I can iterate quickly if you want me to test stuff.

**Comment by ossama-othman** [comment]
I tried bootstrapping mptcpd with autoconf 2.71.  Other than replacing the deprecated AC_PROG_CC_STDC macro call with AC_PROG_CC.  It worked fine.  The change is in pull request #189.

I doubt that change will be enough to address the problems you ran into.  I'll keep digging.

**Comment by teto** [comment]
actually adding autoconf-archive to the dependency fixed it. Hard to find out with the log I posted earlier but checking my inputs against the readme made me realize it. Thanks for the help.

**Comment by ossama-othman** [comment]
Great!  I'm glad it was an easy fix.

**Comment by teto** [comment]
I am the author of a path manager but for the out-of-tree kernel (at https://github.com/teto/quantum2/tree/main/mptcp-pm). I am looking at porting it to support linux-net-next. Meanwhile, is there a plugin for mptcpd that creates new subflows with the same IPs but different ports  ? (for simple MPTCP testing on localhost)
