### ISSUE TITLE
Install `libmptcpwrap.so` in a dedicated directory

### ISSUE THREAD

**Issue by matttbe** [intel/mptcpd#202]
**Describe the bug**
For the moment, `libmptcpwrap.so` is installed with mptcpd plugins. It looks cleaner to install it in a dedicated directory

**To Reproduce**
`make install`

**Expected behavior**
It will be easier for the packaging to have dedicated directory because we need to split into different packages.

**Desktop (please complete the following information):**
 - Debian / Ubuntu packaging

**Additional context**
Packaging mptcpd for Debian and cie.

**Comment by ossama-othman** [comment]
The following patch should provide the desired behavior:
```diff
diff --git a/src/Makefile.am b/src/Makefile.am
index 2b37d8a..8fafd59 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -62,7 +62,8 @@ else
 bin_PROGRAMS = mptcpd mptcpize
 endif
 
-pkglib_LTLIBRARIES = libmptcpwrap.la
+mptcpizedir = $(libdir)/mptcpize
+mptcpize_LTLIBRARIES = libmptcpwrap.la
 
 mptcpd_SOURCES = mptcpd.c
 mptcpd_LDADD   =  
```
`libmptcpwrap.*` will end up being installed in `$(libdir)/mptcpize`.

**Comment by ossama-othman** [comment]
This relates to Debian packaging related changes in #200.

**Comment by ossama-othman** [comment]
@dcaratti Would this work for the Fedora package, too?

**Comment by dcaratti** [comment]
> @dcaratti Would this work for the Fedora package, too?

I think yes, it should work  with proper adjustments of the specfile.

**Comment by matttbe** [comment]
@ossama-othman thank you for the nice patch, it works as expected!

**Comment by ossama-othman** [comment]
> @ossama-othman thank you for the nice patch, it works as expected!
> 
> I guess because you wrote the patch, you will submit it, right? :)

Haha, sure. :+1:
