### ISSUE TITLE
Make unit tests working on any kernel hosts

### ISSUE THREAD

**Issue by matttbe** [intel/mptcpd#204]
**Describe the bug**
Related to #200, it is recommended to execute the unit tests when packaging an application for Debian/Ubuntu. From what I understand, tests will run in a "chroot" environment it seems we cannot control the host kernel.

**To Reproduce**
For example, if the host kernel is a v5.4 one, these tests are failing: test-path-manager, test-commands, test-mptcpwrap.

**Expected behavior**
Maybe skipping these tests if the kernel is not one that is supported would allow me to run all tests instead of disabling some of them on all builds.

**Additional context**
Debian/Ubuntu packaging, #200 

```
======================================
   mptcpd 0.8: tests/test-suite.log
======================================

# TOTAL: 17
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-path-manager
=======================

configuration.c:check_file_perms() File "/etc/mptcpd/mptcpd.conf" does not exist.
configuration.c:parse_config_file() Unable to load mptcpd settings from file '/etc/mptcpd/mptcpd.conf'
configuration.c:mptcpd_config_create() path manager plugin directory: tests/plugins/noop/.libs
Required kernel MPTCP support not available.
test-path-manager: test-path-manager.c:92: test_pm_create: Assertion `info->pm != NULL' failed.
FAIL test-path-manager (exit status: 134)

FAIL: test-commands
===================

tests/.libs/test-commands: bind of test address 192.0.2.1 to interface 1 failed: Unknown error -1
configuration.c:check_file_perms() File "/etc/mptcpd/mptcpd.conf" does not exist.
configuration.c:parse_config_file() Unable to load mptcpd settings from file '/etc/mptcpd/mptcpd.conf'
configuration.c:mptcpd_config_create() path manager plugin directory: tests/plugins/noop/.libs
Required kernel MPTCP support not available.
test-commands: test-commands.c:473: setup_tests: Assertion `info->pm' failed.
FAIL test-commands (exit status: 134)

FAIL: test-mptcpwrap
====================

Test case 0: PASS
Test case 1: PASS
Test case 2: PASS
Test case 3: mptcpwrap: changing socket protocol from 0x0 to 0x106 (IPPROTO_MPTCP) for family 0x2 type 0x1 fd -1
ERROR: socket() call failed unexpectedly.
FAIL test-mptcpwrap (exit status: 1)
```

**Comment by matttbe** [comment]
For the last test (mptcpwrap), this commit might fix the issue: https://github.com/intel/mptcpd/pull/203/commits/321bad53a8d29233cd979e4eda81ccbfe9f9ada7 (but I think you need a bit more, see my comment on the PR)

But maybe we want a "skip" instead of a "pass"?

**Comment by ossama-othman** [comment]
I don't think we can skip tests without patching since the generated `Makefile` doesn't support that, AFAICT, but we can declare tests that are expected to fail.  Something like the following can be used to invert the result of tests that are failing:
```
make check XFAIL_TESTS="test-commands test-path-manager"
```
Assuming the two tests listed above are failing, the test suite summary would look like the following:
```
============================================================================
Testsuite summary for mptcpd 0.8
============================================================================
# TOTAL: 17
# PASS:  15
# SKIP:  0
# XFAIL: 2
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to mptcp@lists.linux.dev
============================================================================
```
The exit status for the `make check` would then be `0`, i.e. a successful run.

**Comment by matttbe** [comment]
@ossama-othman thank you for your reply and the idea!

I cannot easily use `XFAIL_TESTS` in my case because I don't know which host kernel will be used to package mptcpd: I could have a "recent" kernel and have all tests passing or an older one where the 3 tests fail. If I set `XFAIL_TESTS`, it will be OK with old kernels but not with recent ones :)

Here is the workaround I used:

```
# Some tests require a recent enough kernel to be validated. If the host kernel
# doesn't support creating MPTCP sockets or have the PM not supporting one
# feature or another, the following tests are going to fail. Easier to ignore
# them for the moment.
TESTS = $(notdir $(basename $(wildcard tests/test-*)))
TESTS_KERNEL = test-path-manager test-commands test-mptcpwrap

override_dh_auto_test:
        make check VERBOSE=1 TESTS='$(filter-out $(TESTS_KERNEL),$(TESTS))'
        make check VERBOSE=1 TESTS='$(TESTS_KERNEL)' || true
```

In other words, we always ignore these 3 tests which is not perfect but I guess this workaround will be OK for Debian: better than nothing!

Hopefully we don't need to change this list too often :)

If you prefer not to skip some tests if the kernel is not supporting some required features, feel free to close this ticket as "wont-fix".

**Comment by ossama-othman** [comment]
Perhaps we should modify these tests so that they don't fail when running on a kernel without MPTCP support.

**Comment by matttbe** [comment]
I was looking a bit at this issue but I just realised libcheck doesn't support marking tests as "skip" (no `ck_skip()`) even if it prints the number of skipped tests in the summary and PR have been sent for that but not applied. Is this correct? :)

**Comment by ossama-othman** [comment]
I looked into test skipping a bit more.  The Automake documentation isn't very clear about it so I dove in to the Automake `test-driver` script source to see how tests are marked as skipped, and found the following:
```sh
case $tweaked_estatus:$expect_failure in
  0:yes) col=$red res=XPASS recheck=yes gcopy=yes;;
  0:*)   col=$grn res=PASS  recheck=no  gcopy=no;;
  77:*)  col=$blu res=SKIP  recheck=no  gcopy=yes;;
  99:*)  col=$mgn res=ERROR recheck=yes gcopy=yes;;
  *:yes) col=$lgn res=XFAIL recheck=no  gcopy=yes;;
  *:*)   col=$red res=FAIL  recheck=yes gcopy=yes;;
esac
```
This shows that a exit status of `77` corresponds to a `SKIP` test result, so I tried the following _hack_ to test the `77` exit code:
```diff
diff --git a/tests/test-commands.c b/tests/test-commands.c
index 0088d8b..07b9519 100644
--- a/tests/test-commands.c
+++ b/tests/test-commands.c
@@ -630,7 +630,7 @@ int main(void)
         mptcpd_pm_destroy(info.pm);
         mptcpd_config_destroy(info.config);
 
-        return l_main_exit() ? 0 : -1;
+        return l_main_exit() ? 77 : -1;
 }
```
and got the following test summary:
```
make[4]: Entering directory '/home/ossama/work/mptcpd/worktrees/init-d-script/tests'
...
PASS: test-path-manager
SKIP: test-commands
PASS: test-configuration
...
============================================================================
Testsuite summary for mptcpd 0.8
============================================================================
# TOTAL: 17
# PASS:  16
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
What do you think about leveraging the `77` exit code to mark the test as `SKIP` if we know the test can't be run due to missing MPTCP support?

**Comment by matttbe** [comment]
Nice!
Yes, good idea to use the `77` exit code!

It strange this is not "properly" documented.

**Comment by ossama-othman** [comment]
> Nice! Yes, good idea to use the `77` exit code!
> 
> It strange this is not "properly" documented.

Yeah, it's a little too "magic".  :)

**Comment by ossama-othman** [comment]
It turns out Automake does document the exit codes under the [Scripts-based Testsuites](https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html) section in its manual.  Using the proper Web search terms helped.    :)

**Comment by matttbe** [comment]
> It turns out Automake does document the exit codes under the [Scripts-based Testsuites](https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html) section in its manual. Using the proper Web search terms helped. :)

Thank you for the link, good to know :-)

**Comment by ossama-othman** [comment]
Pull request #216 also addresses a part of the issue.
