### ISSUE TITLE
test-network-monitor: test-network-monitor.c:290: main: Assertion `data.count > 0' failed.

### ISSUE THREAD

**Issue by candrews** [intel/mptcpd#208]
**Describe the bug**
Running the mptcp 0.9 test suite, the `test-network-monitor` test fails, from `tests/test-suite.log`:
```
FAIL: test-network-monitor
==========================

test-network-monitor: test-network-monitor.c:290: main: Assertion `data.count > 0' failed.
FAIL test-network-monitor (exit status: 134)
```

**To Reproduce**
1. Get mptcp 0.9
2. Run `make check` as described in the `README.md`

**Expected behavior**
All tests should pass

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Linux Kernel: 5.15.12
 - Compiler: gcc (Gentoo 11.2.1_p20220115 p4) 11.2.1 20220115

**Additional context**
[test-suite.log](https://github.com/intel/mptcpd/files/7967381/test-suite.log)
[build.log](https://github.com/intel/mptcpd/files/7967383/build.log)

**Comment by ossama-othman** [comment]
It looks like the `assert()` in the test is triggered because the mptcpd network monitor was unable to find non-loopback network interfaces.  Do you have a non-loopback network interface on your Gentoo box?

For reference, this is what my `test-network-monitor` output looks like:
```
test-network-monitor.c:check_interface() 
interface
  family: 0
  type:   1
  index:  2
  flags:  0x00011043
  name:   enp3s0
test-network-monitor.c:check_interface()   addrs:
test-network-monitor.c:dump_addr()     192.168.1.48
test-network-monitor.c:dump_addr()     fd68:b197:9fe1:4727:d2b2:6d1a:21dc:61a
test-network-monitor.c:dump_addr()     fd68:b197:9fe1:4727:f220:c186:21c0:dbc3
test-network-monitor.c:dump_addr()     fd68:b197:9fe1:4727:7755:b435:42b6:fa7d
test-network-monitor.c:dump_addr()     fd68:b197:9fe1:4727:d79e:2600:23ac:bce5
test-network-monitor.c:dump_addr()     fe80::5d81:62a3:414a:484d
PASS test-network-monitor (exit status: 0)
```

**Comment by candrews** [comment]
> Do you have a non-loopback network interface on your Gentoo box?

I definitely do :)

```
# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether d0:50:99:87:75:b5 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 7c:5c:f8:b2:5a:fc brd ff:ff:ff:ff:ff:ff
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500
    link/none 
```

**Comment by ossama-othman** [comment]
Ha!  I figured as much.  It'd be really odd if you didn't. :)

I'm not sure why `test-network-monitor` is failing for you.  I'll keep digging.

**Comment by ossama-othman** [comment]
Can you attach your kernel `.config` file?  I'd like to compare kernel configs.

**Comment by candrews** [comment]
> Can you attach your kernel `.config` file? I'd like to compare kernel configs.

Certainly - here you go, straight from `/proc/config.gz`: [config.gz](https://github.com/intel/mptcpd/files/7981408/config.gz)

**Comment by matttbe** [comment]
I also get this error when running from a chroot (pbuild to build debian packages). But I guess it is normal without network interfaces.

**Comment by candrews** [comment]
Ah! Yes, I'm also running the tests in a sandbox.

Would it be possible for the test to be modified so it works inside a sandbox which only exposes the loopback interface?

**Comment by ossama-othman** [comment]
Sure.  We can do that.
