### ISSUE TITLE
Automatically enable netlink path manager

### ISSUE THREAD

**Issue by ossama-othman** [intel/mptcpd#36]
**Is your feature request related to a problem? Please describe.**
When using the multipath-tcp.org kernel, it may be necessary to explicitly enable the `netlink` path manager In order for the Multipath TCP Daemon - `mptcpd` - to be used as the path manager for multipath TCP connections.

**Describe the solution you'd like**
`mptcpd` should enable MPTCP and the `netlink` path manager at run-time if their corresponding entries in `/proc/sys/net/mptcp/` exist. Specific `mptcpd` should do the following:

* write `1` to `/proc/sys/net/mptcp/mptcp_enabled`
* write `netlink` to `/proc/sys/net/mptcp/mptcp_path_manager`

**Describe alternatives you've considered**
Write a script to perform the same operations through the [`sysctl`](https://linux.die.net/man/8/sysctl) command, e.g.:
```sh
#!/bin/sh

sysctl -w net.mptcp.mptcp_enabled=1 net.mptcp.mptcp_path_manager=netlink
```
Documenting the necessary `sysctl` command would be useful, too.

**Comment by ossama-othman** [comment]
It looks like more than the `CAP_NET_ADMIN` capability may be needed to be able to write to the files mentioned above since they are owned by `root` with `644` permissions.  Having `mptcpd` itself do the run-time kernel configuration may not be feasible if we are to limit it to the `CAP_NET_ADMIN` capability.  Maintaining that limited capability is desirable.

**Comment by ossama-othman** [comment]
At the very least, `mptcpd` should issue a warning about the improperly configured kernel.

**Comment by matttbe** [comment]
Hello @ossama-othman 

That's a good point!
From my point of view, the daemon should not change sysctl but warn/stop if the configuration is not OK.

But I guess if the daemon modifies the sysctl and it is written in the doc, it is also fine.

But if you change the sysctl `mptcp_enabled`, I don't know if it is a good idea to impose 1. It could be 2: http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP

**Comment by ossama-othman** [comment]
Hi @matttbe,

Thanks for pointing out the `mptcp_enabled = 2` option.  That is indeed the better way to go.  I had incorrectly assumed that `mptcp_enabled` was a boolean value.  In any case, I think that you are correct that the daemon should probably not modify the `sysctl` variables.

For security reasons, we also don't want the daemon to run as `root`, meaning it regardless wouldn't be able modify those variables, as far as I can tell.

I'll instead push a patch that issues a warning.

Thanks again!

**Comment by ossama-othman** [comment]
@matttbe,

On a related note, should the kernel only allow its MPTCP `sysctl` variables to be modified if the process doing so has the `CAP_NET_ADMIN` capability?  For example, writing to the `vm.mmap_min_addr` `sysctl` variable requires the `CAP_SYS_RAWIO` capability:

```c
int mmap_min_addr_handler(struct ctl_table *table, int write,
			  void __user *buffer, size_t *lenp, loff_t *ppos)
{
	int ret;

	if (write && !capable(CAP_SYS_RAWIO))
		return -EPERM;

	ret = proc_doulongvec_minmax(table, write, buffer, lenp, ppos);

	update_mmap_min_addr();

	return ret;
}
```
This implies a `root` process could have downgraded capabilities.  Should we do something similar in the MPTCP `sysctl` handlers in `mptcp_ctrl.c`?

**Comment by matttbe** [comment]
> On a related note, should the kernel only allow its MPTCP sysctl variables to be modified if the process doing so has the CAP_NET_ADMIN capability?

That's a good question. I don't know what are the recommendations on this security subject.
I don't know if we can allow a non root user to change these parameters. I guess the same applies to other `net` sysctl :-/

>  For example, writing to the vm.mmap_min_addr sysctl variable requires the CAP_SYS_RAWIO capability:

Does that mean we need to redefine all default `proc_handler`'s we use in `mptcp_ctrl.c`. Maybe we can do that for `mptcp_path_manager` only?

**Comment by ossama-othman** [comment]
As discussed in PR #37, mptcpd will not automatically enable the netlink path manager, and will instead warn the user about incorrect MPTCP kernel configuration.
