### ISSUE TITLE
OpenWrt support

### ISSUE THREAD

**Issue by khmtambi** [intel/mptcpd#38]
Please provide OpenWrt support for this software along with its Makefile to include in the package list that can be selected from menuconfig.

**Comment by ossama-othman** [comment]
Hi @khmtambi,

Would you please clarify what it is you're expecting that isn't already provided by `mptcpd`?

From what I understand, OpenWRT provides build infrastructure for autotool-enabled software distributions, such as `mptcpd` and it's dependencies, [`ELL`](https://01.org/ell) and [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/).

The OpenWRT kernel maintainers would have to pull in the MPTCP-enabled kernel at [multipath-tcp.org](https://multipath-tcp.org) or [mptcp-net-next](https://github.com/multipath-tcp/mptcp_net-next) kernel currently under development.  The latter is not yet supported by `mptcpd`.

Thanks!

**Comment by khmtambi** [comment]
Hi,

Thanks for such a quick response really! ok so I have managed to apply the patch which allows me to use mptcp with my openwrt kernel 4.19. it is working like a charm. so that is not really a problem.
I was asking how to compile this mptcpd in openwrt. as far as I have understand (forgive me if I am wrong being a noob) mptcpd is using ELL as dynamic library right? but ELL is not there in openwrt. not in menuconfig. pkg-config is there but not ELL.

**Comment by khmtambi** [comment]
Ok so I did some research and included mptcpd and ell in the openwrt build structure. while ell compiles successfully I had first faced the problem that .configure in mptcpd was not detecting ell. so after meddling with a bit of things I found that the .pc file for ELL was not included as i had no rule to include that file in the staging_dir. 
so this part is done and the .configure is working./ here is my output of the .configure
https://pastebin.com/nbTFJz7M

but as you can see in the above link that at the end it says 
make[3]: *** No rule to make target 'mptcpd'.  Stop.

dont know why. it could be because of my Makefile for mptcpd or something. please guide

**Comment by khmtambi** [comment]
ok so I have managed to compile both the ELL and mptcpd in openwrt which is running mptcp 0.95. all the library and files are there as well as the plugin. one thing is confusing to me. in the description you mentioned that :

> It interacts with the Linux kernel through a generic netlink connection to track per-connection information (e.g. available remote addresses), available network interfaces, request new MPTCP subflows, handle requests for subflows, etc.
does this mean that user will be able to control the mptcp subflows? as I see the options to use this daemon it is just running and I dont see any subflow control option. please correct me if I am wrong. 

Thanks!

**Comment by ossama-othman** [comment]
Path management strategies that control subflow creation, destruction, and priority are implemented through `mptcpd` plugins.  Those plugins would call the functions in [`<mptcpd/path_manager.h>`](https://github.com/intel/mptcpd/blob/master/include/mptcpd/path_manager.h), e.g.:

```c
/**
 * @brief Send @c MPTCP_GENL_CMD_ADD_SUBFLOW genl command to kernel.
 *
 * @param[in] pm                The mptcpd path manager object.
 * @param[in] token             MPTCP connection token.
 * @param[in] local_address_id  MPTCP local address ID.
 * @param[in] remote_address_id MPTCP remote address ID.
 * @param[in] local_addr        MPTCP subflow local address
 *                              information, including the port.
 * @param[in] remote_addr       MPTCP subflow remote address
 *                              information, including the port.
 * @param[in] backup            Whether or not to set the MPTCP
 *                              subflow backup priority flag.
 *
 * @return @c true if operation was successful. @c false otherwise.
 *
 * @todo There far too many parameters.  Reduce.
 */
MPTCPD_API bool
mptcpd_pm_add_subflow(struct mptcpd_pm *pm,
                      mptcpd_token_t token,
                      mptcpd_aid_t local_address_id,
                      mptcpd_aid_t remote_address_id,
                      struct mptcpd_addr const *local_addr,
                      struct mptcpd_addr const *remote_addr,
                      bool backup);
```
`mptcpd` plugins implement the interface defined in [`<mptcpd/plugin.h>`](https://github.com/intel/mptcpd/blob/master/include/mptcpd/plugin.h).  See the [`plugins/path_managers/sspi.c`](https://github.com/intel/mptcpd/blob/master/plugins/path_managers/sspi.c) for an example.

Keep in mind `mptcpd` is still in alpha, and its APIs are subject to change.

**Comment by ossama-othman** [comment]
Is your goal to experiment with MPTCP path management in the user space, or simply to experiment with MPTCP?  If it's the latter, you only need the MPTCP-enabled kernel since it provides built-in path management strategies (e.g. `fullmesh`), in addition to the `netlink` path manager used by `mptcpd`.  You'd only use `mptcpd` for path management in the user space.

**Comment by khmtambi** [comment]
My requirement is to use in the userspace. indeed the full mesh is there in kernel and is working. but I have a problem in my current situation that the subflow just drops after a random period of time. so I thought thgouth this software I could list the subflows and decide which subflow to revive once it is down. can mptcpd allow me to do this? I dont want to implement the full path management strategy. just to resolve this issue which I am facing for quite some time

**Comment by matttbe** [comment]
> but I have a problem in my current situation that the subflow just drops after a random period of time.

You might be interested by this modification (you need mptcp_v0.95): https://github.com/multipath-tcp/mptcp/commit/ed3036438443a7bcd8d2d0169a012d5595baed75#diff-a7254cb61e2e7c9d02f67dcd8f4e8a94

If it is not re-created, it might be due to another error. That might be interesting to know which one.

**Comment by khmtambi** [comment]
> > but I have a problem in my current situation that the subflow just drops after a random period of time.
> 
> You might be interested by this modification (you need mptcp_v0.95): [multipath-tcp/mptcp@ed30364#diff-a7254cb61e2e7c9d02f67dcd8f4e8a94](https://github.com/multipath-tcp/mptcp/commit/ed3036438443a7bcd8d2d0169a012d5595baed75#diff-a7254cb61e2e7c9d02f67dcd8f4e8a94)
> 
> If it is not re-created, it might be due to another error. That might be interesting to know which one.

I already have done this. updated my 0.94 to 0.95. perhaps you could provide something in this software that can allow me to list the subflows, connected subflows?
like #mptcpd list
or #mptcpd join from userspace?

**Comment by ossama-othman** [comment]
> My requirement is to use in the userspace. indeed the full mesh is there in kernel and is working. but I have a problem in my current situation that the subflow just drops after a random period of time. so I thought thgouth this software I could list the subflows and decide which subflow to revive once it is down. can mptcpd allow me to do this? I dont want to implement the full path management strategy. just to resolve this issue which I am facing for quite some time

You'd have to implement a `mptcpd` plugin to do this sort of thing.  `mptcpd` itself currently just provides a user space path management framework, and a sample/reference plugin.  It also requires that the `netlink` path manager in the kernel be selected to function as expected.

> > If it is not re-created, it might be due to another error. That might be interesting to know which one.
>
> I already have done this. updated my 0.94 to 0.95. perhaps you could provide something in this software that can allow me to list the subflows, connected subflows?
like #mptcpd list
or #mptcpd join from userspace?

The current MPTCP kernel and user space APIs don't provide a way to perform these sorts of on-demand queries, so there is no way for `mptcpd` to do this sort of thing.  As far as I can tell, the only way to get close to what you want is to implement a `mptcpd` plugin that tracks and handles connections and subflows per your needs.

If you still have problems with the `fullmesh` path manager I'd suggest following up on the [mptcp-dev](https://listes-2.sipr.ucl.ac.be/sympa/info/mptcp-dev) mailing list since it's not something `mptcpd` deals with, and since the core kernel developers for the multipath-tcp.org kernel are on that list.
