### ISSUE TITLE
Can't bootstrap

### ISSUE THREAD

**Issue by wapsi** [intel/mptcpd#45]
I can't bootstrap the source code I've pulled from the git, it ends up with this error:
> $ ./bootstrap
> libtoolize: putting auxiliary files in '.'.
> libtoolize: linking file './ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
> libtoolize: linking file 'm4/libtool.m4'
> libtoolize: linking file 'm4/ltoptions.m4'
> libtoolize: linking file 'm4/ltsugar.m4'
> libtoolize: linking file 'm4/ltversion.m4'
> libtoolize: linking file 'm4/lt~obsolete.m4'
> configure.ac:25: error: possibly undefined macro: AC_SUBST
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: /opt/rh/autotools-latest/root/usr/bin/autoconf failed with exit status: 1

I've reproduced this in CentOS 7.6. I also tried this on Debian 10 and it ended up in the same error.

Version information:
autoconf / autoreconf: 2.69
automake: 1.16.1
autoconf-archive: 2017.03.21
libell: 0.22
libtool: 2.4.6
pkg-config: 0.29
gcc: tried with 4.8.5 and 7.3.1

**Comment by ossama-othman** [comment]
Bootstrapping works fine on my Ubuntu 19.04 box:
```
$ git clone git@github.com:intel/mptcpd.git        
Cloning into 'mptcpd'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 263 (delta 17), reused 25 (delta 12), pack-reused 228
Receiving objects: 100% (263/263), 179.10 KiB | 2.71 MiB/s, done.
Resolving deltas: 100% (132/132), done.
$ cd mptcpd/
$ ./bootstrap 
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:36: installing './compile'
configure.ac:36: installing './config.guess'
configure.ac:36: installing './config.sub'
configure.ac:34: installing './install-sh'
configure.ac:34: installing './missing'
Makefile.am: installing './INSTALL'
lib/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
```
The `AC_SUBST` macro is provided by Autoconf itself, not mptcpd, so it's not clear why Autoconf can't find the macro.  Is your autotools installation by chance non-standard?  What happens if you explicitly add the directory containing the Autoconf macros to the `autoreconf` search path, instead of running `bootstrap`, e.g.:
```
$ autoreconf -isf -I /usr/share/autoconf
```

**Comment by wapsi** [comment]
Ah, I was missing autoconf-archive from my Debian 10 box. Now it boostraps OK on Debian but I think on CentOS 7.6 the stock autoconf-archive package is too outdated because it fails even I've autoconf-archive installed.

CentOS 7.6:
`autoconf-archive-2017.03.21-1.el7.noarch`

Debian 10:
`autoconf-archive                 20180313-1`

**Comment by wapsi** [comment]
And maybe this isn't related but the compilation fails on CentOS 7.6 too:
```
make[1]: Entering directory '/root/mptcpd/mptcpd-git-20190914/lib'
  CC       libmptcpd_la-network_monitor.lo
network_monitor.c: In function ‘is_interface_ready’:
network_monitor.c:402:47: error: ‘IFF_UP’ undeclared (first use in this function); did you mean ‘IFLA_MAP’?
         static unsigned int const iff_ready = IFF_UP | IFF_RUNNING;
                                               ^~~~~~
                                               IFLA_MAP
network_monitor.c:402:47: note: each undeclared identifier is reported only once for each function it appears in
network_monitor.c:402:56: error: ‘IFF_RUNNING’ undeclared (first use in this function)
         static unsigned int const iff_ready = IFF_UP | IFF_RUNNING;
                                                        ^~~~~~~~~~~
network_monitor.c:405:38: error: ‘IFF_LOOPBACK’ undeclared (first use in this function); did you mean ‘IN_LOOPBACKNET’?
                 && (ifi->ifi_flags & IFF_LOOPBACK) == 0;
                                      ^~~~~~~~~~~~
                                      IN_LOOPBACKNET
network_monitor.c:406:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
```
I guess this is related to outdated C compiler or something similar?

**Comment by ossama-othman** [comment]
I'm not sure about the CentOS 7.6 older autoconf-archive package.  From what I recall, mptcpd should bootstrap with at least the 2017.09.28 Autoconf Archive release.  A Web search of errors related to a missing `AC_SUBST` macro point to a missing pkgconfig package, which is a bit odd since `AC_SUBST` is provided by Autoconf.  Perhaps there's a M4/Autoconf parsing quirk involved.  I'm not a M4 expert, so I can't be sure.

**Comment by ossama-othman** [comment]
Regarding the network interface flags, they are part of the C library, and should be defined in `<net/if.h>`.  In `mptcpd/lib/network_monitor.c` they are pull in like so:
```c
#define _DEFAULT_SOURCE  ///< For standard network interface flags.
...
#include <net/if.h>  // For standard network interface flags.
```
Can you confirm that those flags exist in the `<net/if.h>` header?  On my box, they are in `/usr/include/net/if.h`:
```c
#ifdef __USE_MISC
/* Standard interface flags. */
enum
  {
    IFF_UP = 0x1,		/* Interface is up.  */
# define IFF_UP	IFF_UP
...
    IFF_RUNNING = 0x40,		/* Resources allocated.  */
# define IFF_RUNNING	IFF_RUNNING
...
  };
```
Defining `_DEFAULT_SOURCE` causes `__USE_MISC` to be defined (see `<features.h>`).

**Comment by wapsi** [comment]
Yes, I've /usr/include/net/if.h in place and it's part of the glibc-headers-2.17-260.el7_6.6.x86_64 package and it does have those IFF_UP, IFF_RUNNING and IN_LOOPBACKNET defined:

```
#ifdef __USE_MISC
/* Standard interface flags. */
enum
  {
    IFF_UP = 0x1,               /* Interface is up.  */
# define IFF_UP IFF_UP
```
```
    IFF_LOOPBACK = 0x8,         /* Is a loopback net.  */
# define IFF_LOOPBACK   IFF_LOOPBACK
```
```
    IFF_RUNNING = 0x40,         /* Resources allocated.  */
# define IFF_RUNNING    IFF_RUNNING
```
And __USE_MISC is found from /usr/include/features.h Could glibc be too outdated then? CentOS 7.6 is using version 2.17 where Debian 10 has 2.28?

**Comment by ossama-othman** [comment]
I took a look at the [glibc 2.17 <features.h>](https://sourceware.org/git/?p=glibc.git;a=blob;f=include/features.h;h=b624d36cd26a9885bb01cbcffe2efdf1fa4e65d8;hb=c758a6861537815c759cba2018a3b1abb1943842#l303) header.  The `__USE_MISC` feature test macro is only defined in glibc 2.17 if `_BSD_SOURCE` or `_SVID_SOURCE` is defined:
```c
 304 #if defined _BSD_SOURCE || defined _SVID_SOURCE
 305 # define __USE_MISC     1
 306 #endif
```
Those feature test macros were deprecated in [glibc .20](https://sourceware.org/git/?p=glibc.git;a=blob;f=include/features.h;h=390001642852f56581ff1d9abdfa5f3b82f693b5;hb=HEAD#l180):
```c
 181 /* _BSD_SOURCE and _SVID_SOURCE are deprecated aliases for
 182    _DEFAULT_SOURCE.  If _DEFAULT_SOURCE is present we do not
 183    issue a warning; the expectation is that the source is being
 184    transitioned to use the new macro.  */
 185 #if (defined _BSD_SOURCE || defined _SVID_SOURCE) \
 186     && !defined _DEFAULT_SOURCE
 187 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
 188 # undef  _DEFAULT_SOURCE
 189 # define _DEFAULT_SOURCE        1
 190 #endif
```
For your Centos 7.6 build, try adding _BSD_SOURCE to CPPFLAGS, e.g.:
```sh
$ ./configure CPPFLAGS=-D_BSD_SOURCE
```
or by applying the following patch:
```diff
diff --git a/lib/network_monitor.c b/lib/network_monitor.c
index 866fbda..35a3022 100644
--- a/lib/network_monitor.c
+++ b/lib/network_monitor.c
@@ -9,6 +9,7 @@
 
 #define _POSIX_C_SOURCE 200112L  ///< For XSI-compliant strerror_r().
 #define _DEFAULT_SOURCE  ///< For standard network interface flags.
+#define _BSD_SOURCE
 
 #include <string.h>
 #include <stdlib.h>
```
The patch doesn't trigger the deprecation warning on my Linux box with glibc 2.29 installed.  If it works for you, I'll submit a pull request, accordingly.

HTH!

**Comment by ossama-othman** [comment]
@wapsi Are you still having issues with bootstrapping `mptcpd`?

**Comment by wapsi** [comment]
Not anymore. This issue can be closed.
