### ISSUE TITLE
How can the path manager immediately create or close a subflow when the network monitor listens for a change in the network interface or network address?

### ISSUE THREAD

**Issue by Fistw** [intel/mptcpd#67]
MPTCPD is an amazing project. I'm trying to use it. I want to write a plugin similar to mptcp_fullmesh. The plugin needs to create or destroy the subflow by listening for changes in the network interface or network address. But this functionality is not provided in the API.

The network monitor in the source code listens for changes in the network interface or network address to modify interfacesinfo, but does not provide a callback interface for the plugin.

How can I finish this work?Thanks for your reply.

**Comment by Fistw** [comment]
I have found the latest pull#64 and will try to use it.Look forward to the success of the pull.thank you

**Comment by ossama-othman** [comment]
Thanks for giving PR #64 a try.  It was merged to the master branch a few days.  You may also be interested in PR #69 that adds a function triggers a `REMOVE_ADDR` command in the kernel.

Please let me know if you run into any issues.
