### ISSUE TITLE
mptcpd will not work with ELL > 0.33 due to removed plugin API

### ISSUE THREAD

**Issue by ossama-othman** [intel/mptcpd#84]
**Describe the bug**
The pending ELL 0.34 release r[emoves the `l_plugin` API](https://git.kernel.org/pub/scm/libs/ell/ell.git/commit/?id=e129cb4cd2270f308c1564e75859672643dd902b) meaning mptcpd's plugin framework will need to need to find an alternative.

**To Reproduce**
1. Build mptcpd against ELL > 0.33.

**Expected behavior**
Mptcpd should compile clean against ELL > 0.33, and the mptcpd plugin test should succeed.

**Comment by dcaratti** [comment]
@ossama-othman , would it be possible to build/run mptcpd without any plugin? that  would speed-up the [specfile](https://bugzilla.redhat.com/show_bug.cgi?id=1899884). Thanks!

**Comment by ossama-othman** [comment]
@dcaratti I just created a [mptcpd 0.5.1](https://github.com/intel/mptcpd/releases/tag/v0.5.1) minor release that contains the back-ported plugin framework changes from the upcoming 0.6 release that allow mptcpd to be built against versions of ELL > 0.33.

Note that 0.5.1 only contains the ELL > 0.33 support, and does not contain the changes that support the upstream Linux kernel netlink path management API found in the upcoming 0.6 release.

**Comment by dcaratti** [comment]
> @dcaratti I just created a [mptcpd 0.5.1](https://github.com/intel/mptcpd/releases/tag/v0.5.1) minor release that contains the back-ported plugin framework changes from the upcoming 0.6 release that allow mptcpd to be built against versions of ELL > 0.33.
thanks @ossama-othman , I confirm that it [builds](https://copr.fedorainfracloud.org/coprs/dcaratti/mptcpd/build/1830906/) successfully !
